<div class="row custom-nav">
    <div class="col-12 col-md-10 offset-md-1">
        <nav class="navbar navbar-expand-lg d-lg-flex align-items-lg-end">
			<?php echo $this->getChildHtml("logo"); ?>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
			<?php echo $this->getChildHtml('catalog.topnav'); ?>
		</nav>
	</div>
</div>
<div class="row search">
    <?php echo $this->getChildHtml("topSearch"); ?>
</div>


